tiers:
  - name: 0-Dark Age
    min: 0.0
    max: 1.0
  - name: 1-Shelter
    min: 1.0
    max: 100.0
  - name: 2-Fortress
    min: 100.0
    max: 500.0
  - name: 3-Castle
    min: 500.0
    max: 10000.0

outpost-structure:
  - "0,0,0,AIR"
  - "0,-1,0,CHEST"
  - "1,0,0,COBBLESTONE"
  - "0,0,1,COBBLESTONE"
  - "-1,0,0,COBBLESTONE"
